import type {
  Donation,
  Recipient,
  Volunteer,
  Match,
  AnalyticsData,
  ActivityEvent,
  Donor,
} from "@/types"

/** Minutes offset helper returning an ISO string relative to load time. */
const at = (minutesFromNow: number) =>
  new Date(Date.now() + minutesFromNow * 60000).toISOString()

const donors: Record<string, Donor> = {
  saffron: {
    id: "dn-1",
    name: "Saffron Kitchen",
    type: "restaurant",
    address: "218 Market Street",
  },
  northline: {
    id: "dn-2",
    name: "Northline Cafeteria",
    type: "cafeteria",
    address: "5 Corporate Plaza",
  },
  greenleaf: {
    id: "dn-3",
    name: "Greenleaf Grocers",
    type: "grocer",
    address: "77 Elm Avenue",
  },
  rise: {
    id: "dn-4",
    name: "Rise & Crumb Bakery",
    type: "bakery",
    address: "12 Baker Lane",
  },
  harvest: {
    id: "dn-5",
    name: "Harvest Catering Co.",
    type: "catering",
    address: "400 Convention Way",
  },
}

export const recipients: Recipient[] = [
  {
    id: "rc-1",
    name: "Hope Shelter",
    type: "shelter",
    address: "34 Franklin Road",
    capacity: 100,
    currentLoad: 42,
    preferences: ["vegetarian", "non_vegetarian", "halal"],
    status: "accepting",
    lastDeliveryAt: at(-95),
    mealsReceivedToday: 58,
    location: { x: 68, y: 32, label: "Hope Shelter" },
    contact: "Dana Whitfield",
    phone: "+1 (415) 555-0142",
  },
  {
    id: "rc-2",
    name: "Eastside Community Kitchen",
    type: "community_kitchen",
    address: "9 Harbor Street",
    capacity: 80,
    currentLoad: 64,
    preferences: ["vegetarian", "vegan", "non_vegetarian"],
    status: "near_capacity",
    lastDeliveryAt: at(-210),
    mealsReceivedToday: 64,
    location: { x: 82, y: 58, label: "Eastside Kitchen" },
    contact: "Marcus Lee",
    phone: "+1 (415) 555-0170",
  },
  {
    id: "rc-3",
    name: "St. Anne's Food Bank",
    type: "food_bank",
    address: "61 Cathedral Hill",
    capacity: 240,
    currentLoad: 96,
    preferences: ["vegetarian", "non_vegetarian", "gluten_free", "halal"],
    status: "accepting",
    lastDeliveryAt: at(-40),
    mealsReceivedToday: 132,
    location: { x: 44, y: 70, label: "St. Anne's" },
    contact: "Priya Nair",
    phone: "+1 (415) 555-0188",
  },
  {
    id: "rc-4",
    name: "Bayview Outreach",
    type: "ngo",
    address: "150 Innes Avenue",
    capacity: 60,
    currentLoad: 12,
    preferences: ["vegetarian", "vegan"],
    status: "accepting",
    lastDeliveryAt: at(-720),
    mealsReceivedToday: 12,
    location: { x: 58, y: 84, label: "Bayview Outreach" },
    contact: "Elena Rossi",
    phone: "+1 (415) 555-0155",
  },
  {
    id: "rc-5",
    name: "Mission Family Center",
    type: "shelter",
    address: "22 Valencia Street",
    capacity: 120,
    currentLoad: 118,
    preferences: ["vegetarian", "non_vegetarian", "halal"],
    status: "full",
    lastDeliveryAt: at(-30),
    mealsReceivedToday: 118,
    location: { x: 30, y: 46, label: "Mission Family" },
    contact: "Tomás García",
    phone: "+1 (415) 555-0199",
  },
]

export const volunteers: Volunteer[] = [
  {
    id: "vl-1",
    name: "Aarav Mehta",
    status: "available",
    vehicle: "scooter",
    distanceKm: 1.8,
    completedPickups: 126,
    rating: 4.9,
    etaMinutes: 8,
    location: { x: 40, y: 30, label: "Aarav M." },
    phone: "+1 (415) 555-0110",
    joinedAt: at(-60 * 24 * 210),
    avatarColor: "oklch(0.62 0.13 155)",
  },
  {
    id: "vl-2",
    name: "Sofia Alvarez",
    status: "on_pickup",
    vehicle: "car",
    distanceKm: 3.2,
    completedPickups: 89,
    rating: 4.8,
    currentAssignment: "FD-1042",
    location: { x: 52, y: 44, label: "Sofia A." },
    phone: "+1 (415) 555-0121",
    joinedAt: at(-60 * 24 * 140),
    avatarColor: "oklch(0.6 0.12 250)",
  },
  {
    id: "vl-3",
    name: "Daniel Osei",
    status: "available",
    vehicle: "bike",
    distanceKm: 0.9,
    completedPickups: 204,
    rating: 5.0,
    etaMinutes: 5,
    location: { x: 62, y: 26, label: "Daniel O." },
    phone: "+1 (415) 555-0132",
    joinedAt: at(-60 * 24 * 320),
    avatarColor: "oklch(0.62 0.16 40)",
  },
  {
    id: "vl-4",
    name: "Mei Chen",
    status: "on_pickup",
    vehicle: "van",
    distanceKm: 4.6,
    completedPickups: 58,
    rating: 4.7,
    currentAssignment: "FD-1039",
    location: { x: 24, y: 60, label: "Mei C." },
    phone: "+1 (415) 555-0143",
    joinedAt: at(-60 * 24 * 90),
    avatarColor: "oklch(0.58 0.14 300)",
  },
  {
    id: "vl-5",
    name: "James Okoro",
    status: "offline",
    vehicle: "car",
    distanceKm: 6.1,
    completedPickups: 142,
    rating: 4.9,
    location: { x: 78, y: 72, label: "James O." },
    phone: "+1 (415) 555-0154",
    joinedAt: at(-60 * 24 * 260),
    avatarColor: "oklch(0.55 0.1 210)",
  },
  {
    id: "vl-6",
    name: "Fatima Hassan",
    status: "available",
    vehicle: "scooter",
    distanceKm: 2.3,
    completedPickups: 77,
    rating: 4.8,
    etaMinutes: 11,
    location: { x: 46, y: 66, label: "Fatima H." },
    phone: "+1 (415) 555-0165",
    joinedAt: at(-60 * 24 * 120),
    avatarColor: "oklch(0.6 0.12 145)",
  },
]

export const donations: Donation[] = [
  {
    id: "d-1048",
    code: "FD-1048",
    donor: donors.saffron,
    foodName: "Vegetarian lunch trays",
    category: "prepared",
    quantity: 45,
    unit: "meals",
    dietary: ["vegetarian"],
    preparedAt: at(-150),
    safeUntil: at(102),
    description:
      "45 vegetarian meals from today's lunch service, prepared at 12:30 PM. Rice, dal, seasonal vegetables and flatbread.",
    handlingNotes: "Keep upright. Best served warm.",
    status: "needs_match",
    urgency: "high",
    distanceKm: 2.4,
    matchScore: 94,
    createdAt: at(-8),
    location: { x: 34, y: 24, label: "Saffron Kitchen" },
  },
  {
    id: "d-1047",
    code: "FD-1047",
    donor: donors.northline,
    foodName: "Assorted sandwiches",
    category: "prepared",
    quantity: 60,
    unit: "meals",
    dietary: ["vegetarian", "non_vegetarian"],
    preparedAt: at(-200),
    safeUntil: at(240),
    status: "matched",
    urgency: "medium",
    distanceKm: 3.1,
    recipientId: "rc-3",
    matchScore: 88,
    createdAt: at(-26),
    location: { x: 50, y: 38, label: "Northline Cafeteria" },
  },
  {
    id: "d-1046",
    code: "FD-1046",
    donor: donors.rise,
    foodName: "Bread & pastries",
    category: "bakery",
    quantity: 80,
    unit: "items",
    dietary: ["vegetarian"],
    preparedAt: at(-320),
    safeUntil: at(600),
    status: "driver_assigned",
    urgency: "low",
    distanceKm: 1.2,
    recipientId: "rc-4",
    volunteerId: "vl-3",
    matchScore: 91,
    createdAt: at(-52),
    location: { x: 64, y: 22, label: "Rise & Crumb" },
  },
  {
    id: "d-1045",
    code: "FD-1045",
    donor: donors.greenleaf,
    foodName: "Fresh produce boxes",
    category: "produce",
    quantity: 30,
    unit: "boxes",
    dietary: ["vegan"],
    preparedAt: at(-60),
    safeUntil: at(60),
    status: "at_risk",
    urgency: "critical",
    distanceKm: 5.0,
    matchScore: 72,
    createdAt: at(-15),
    location: { x: 20, y: 52, label: "Greenleaf Grocers" },
  },
  {
    id: "d-1044",
    code: "FD-1044",
    donor: donors.harvest,
    foodName: "Catered buffet surplus",
    category: "prepared",
    quantity: 120,
    unit: "meals",
    dietary: ["vegetarian", "non_vegetarian", "halal"],
    preparedAt: at(-180),
    safeUntil: at(150),
    status: "pickup_in_progress",
    urgency: "high",
    distanceKm: 3.8,
    recipientId: "rc-1",
    volunteerId: "vl-2",
    matchScore: 96,
    createdAt: at(-70),
    location: { x: 56, y: 50, label: "Harvest Catering" },
  },
  {
    id: "d-1042",
    code: "FD-1042",
    donor: donors.northline,
    foodName: "Soup & salad packs",
    category: "prepared",
    quantity: 40,
    unit: "meals",
    dietary: ["vegetarian", "gluten_free"],
    preparedAt: at(-240),
    safeUntil: at(90),
    status: "pickup_in_progress",
    urgency: "medium",
    distanceKm: 2.9,
    recipientId: "rc-2",
    volunteerId: "vl-2",
    matchScore: 85,
    createdAt: at(-88),
    location: { x: 48, y: 40, label: "Northline Cafeteria" },
  },
  {
    id: "d-1039",
    code: "FD-1039",
    donor: donors.greenleaf,
    foodName: "Dairy & yogurt",
    category: "dairy",
    quantity: 50,
    unit: "units",
    dietary: ["vegetarian"],
    preparedAt: at(-400),
    safeUntil: at(300),
    status: "delivered",
    urgency: "low",
    distanceKm: 4.2,
    recipientId: "rc-3",
    volunteerId: "vl-4",
    matchScore: 90,
    createdAt: at(-160),
    location: { x: 22, y: 58, label: "Greenleaf Grocers" },
  },
  {
    id: "d-1037",
    code: "FD-1037",
    donor: donors.saffron,
    foodName: "Rice & curry trays",
    category: "prepared",
    quantity: 75,
    unit: "meals",
    dietary: ["vegetarian", "non_vegetarian"],
    preparedAt: at(-500),
    safeUntil: at(-20),
    status: "delivered",
    urgency: "low",
    distanceKm: 2.1,
    recipientId: "rc-1",
    volunteerId: "vl-1",
    matchScore: 93,
    createdAt: at(-220),
    location: { x: 34, y: 24, label: "Saffron Kitchen" },
  },
]

export const matches: Match[] = [
  {
    id: "m-1",
    donationId: "d-1048",
    recipientId: "rc-1",
    distanceKm: 2.4,
    score: 94,
    capacityFit: 60,
    dietaryCompatible: true,
    windowCompatible: true,
    suggestedVolunteerId: "vl-1",
    reasons: [
      { label: "Closest suitable recipient", satisfied: true },
      { label: "Enough capacity (60 meals available)", satisfied: true },
      { label: "Dietary requirements satisfied", satisfied: true },
      { label: "Pickup window compatible", satisfied: true },
    ],
  },
  {
    id: "m-2",
    donationId: "d-1045",
    recipientId: "rc-4",
    distanceKm: 3.3,
    score: 81,
    capacityFit: 48,
    dietaryCompatible: true,
    windowCompatible: true,
    suggestedVolunteerId: "vl-6",
    reasons: [
      { label: "Accepts vegan produce", satisfied: true },
      { label: "Enough capacity (48 boxes available)", satisfied: true },
      { label: "Pickup window compatible", satisfied: true },
      { label: "Volunteer within 2.3 km", satisfied: true },
    ],
  },
  {
    id: "m-3",
    donationId: "d-1045",
    recipientId: "rc-3",
    distanceKm: 4.9,
    score: 68,
    capacityFit: 144,
    dietaryCompatible: true,
    windowCompatible: false,
    suggestedVolunteerId: "vl-3",
    reasons: [
      { label: "Large capacity headroom", satisfied: true },
      { label: "Dietary requirements satisfied", satisfied: true },
      { label: "Pickup window tight", satisfied: false },
      { label: "Further than nearest option", satisfied: false },
    ],
  },
]

export const activityByDonation: Record<string, ActivityEvent[]> = {
  "d-1048": [
    { id: "a1", time: at(-8), label: "Donation posted by Saffron Kitchen", type: "posted" },
    { id: "a2", time: at(-7), label: "AI analyzed donation — 45 vegetarian meals", type: "analyzed" },
    { id: "a3", time: at(-6), label: "Hope Shelter matched at 94%", type: "matched" },
  ],
  "d-1044": [
    { id: "b1", time: at(-70), label: "Donation posted by Harvest Catering", type: "posted" },
    { id: "b2", time: at(-69), label: "AI analyzed donation — 120 mixed meals", type: "analyzed" },
    { id: "b3", time: at(-67), label: "Hope Shelter matched at 96%", type: "matched" },
    { id: "b4", time: at(-64), label: "Sofia Alvarez assigned as driver", type: "assigned" },
    { id: "b5", time: at(-58), label: "Pickup started", type: "pickup" },
  ],
}

export const activityFeed: ActivityEvent[] = [
  { id: "f1", time: at(-3), label: "FD-1048 matched with Hope Shelter", type: "matched" },
  { id: "f2", time: at(-12), label: "FD-1046 driver assigned — Daniel Osei", type: "assigned" },
  { id: "f3", time: at(-24), label: "FD-1044 pickup started", type: "pickup" },
  { id: "f4", time: at(-41), label: "FD-1039 delivered to St. Anne's Food Bank", type: "delivered" },
  { id: "f5", time: at(-58), label: "FD-1042 driver assigned — Sofia Alvarez", type: "assigned" },
  { id: "f6", time: at(-88), label: "FD-1037 delivered to Hope Shelter", type: "delivered" },
]

const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

export const analytics: AnalyticsData = {
  mealsRescued: 12480,
  foodDivertedTonnes: 4.2,
  co2AvoidedTonnes: 11.6,
  successfulDeliveries: 1284,
  mealsOverTime: [
    { date: "Wk 1", meals: 1680, deliveries: 142 },
    { date: "Wk 2", meals: 1920, deliveries: 168 },
    { date: "Wk 3", meals: 2140, deliveries: 181 },
    { date: "Wk 4", meals: 2360, deliveries: 205 },
    { date: "Wk 5", meals: 2180, deliveries: 194 },
    { date: "Wk 6", meals: 2200, deliveries: 210 },
  ],
  byCategory: [
    { category: "Prepared", meals: 5240 },
    { category: "Produce", meals: 2680 },
    { category: "Bakery", meals: 1920 },
    { category: "Dairy", meals: 1360 },
    { category: "Packaged", meals: 880 },
    { category: "Beverages", meals: 400 },
  ],
  byLocation: [
    { location: "Downtown", meals: 3820 },
    { location: "Eastside", meals: 2940 },
    { location: "Mission", meals: 2510 },
    { location: "Bayview", meals: 1740 },
    { location: "Harbor", meals: 1470 },
  ],
  avgMatchingMinutes: 3.4,
  avgPickupMinutes: 21,
  deliverySuccessRate: 98.2,
  rescueEfficiency: 94,
}

export const weeklyVolunteerActivity = days.map((d, i) => ({
  day: d,
  pickups: [18, 22, 26, 24, 31, 29, 15][i],
}))

// ---- Lookup helpers -------------------------------------------------------

export function getDonation(idOrCode: string): Donation | undefined {
  return donations.find((d) => d.id === idOrCode || d.code === idOrCode)
}

export function getRecipient(id?: string): Recipient | undefined {
  if (!id) return undefined
  return recipients.find((r) => r.id === id)
}

export function getVolunteer(id?: string): Volunteer | undefined {
  if (!id) return undefined
  return volunteers.find((v) => v.id === id)
}

export function getMatchForDonation(donationId: string): Match | undefined {
  return matches.find((m) => m.donationId === donationId)
}

export const kpis = {
  mealsRescuedToday: 842,
  mealsRescuedTrend: 12.4,
  activeDonations: 8,
  activeDonationsTrend: 3,
  pickupsInProgress: 5,
  pickupsTrend: 1,
  foodAtRisk: 3,
  foodAtRiskTrend: -1,
}

export const landingStats = [
  { label: "Meals rescued", value: "12,480" },
  { label: "Food diverted", value: "4.2 tonnes" },
  { label: "Active volunteers", value: "186" },
  { label: "Partner shelters", value: "42" },
]
